module.exports = {
  tabWidth: 2,
  useTabs: false,
  printWidth: 80,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  proseWrap: 'always',
  svelteSortOrder: 'options-scripts-markup-styles',
  svelteStrictMode: true,
  svelteBracketNewLine: true,
  svelteAllowShorthand: false,
  svelteIndentScriptAndStyle: false,
  vueIndentScriptAndStyle: false,
};
